<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculatorProjectTest" project="JunitProject" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="ak.cal.CalculatorProjectTest" time="0.071" displayname="CalculatorProjectTest" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]">
    <testcase name="subTest" classname="ak.cal.CalculatorProjectTest" time="0.036" displayname="subTest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:subTest()]"/>
    <testcase name="AreaOfCircleTest" classname="ak.cal.CalculatorProjectTest" time="0.004" displayname="AreaOfCircleTest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:AreaOfCircleTest()]"/>
    <testcase name="addtest" classname="ak.cal.CalculatorProjectTest" time="0.002" displayname="addtest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:addtest()]"/>
    <testcase name="PositiveNumTest" classname="ak.cal.CalculatorProjectTest" time="0.003" displayname="PositiveNumTest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:PositiveNumTest()]"/>
    <testcase name="mulTest" classname="ak.cal.CalculatorProjectTest" time="0.001" displayname="mulTest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:mulTest()]"/>
    <testcase name="divTest" classname="ak.cal.CalculatorProjectTest" time="0.018" displayname="divTest()" uniqueid="[engine:junit-jupiter]/[class:ak.cal.CalculatorProjectTest]/[method:divTest()]">
      <failure>org.opentest4j.AssertionFailedError: Div Function can calculate two integer ==&gt; Expected java.lang.NullPointerException to be thrown, but nothing was thrown.&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:39)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3131)&#13;
	at ak.cal.CalculatorProjectTest.divTest(CalculatorProjectTest.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
